const r = require('express').Router();
const c = require('../controllers/shopController');
r.get('/products', c.listProducts);
r.post('/cart', c.addToCart);
r.get('/cart', c.viewCart);
r.delete('/cart/:id', c.removeFromCart);
r.post('/checkout', c.checkout);
r.get('/orders', c.listOrders);
r.get('/orders/:id', c.getOrder);
r.post('/pay', c.payOrder);
r.get('/pay/:id', c.paymentStatus);
module.exports = r;
